#######
# Compiled from computercraft/functions/common/damage.mcscript
# to .//data/computercraft/functions/common/damage.mcfunction
#
# Generated by Minecraft Script for 1.13
######
effect give @s minecraft:absorption 1 0 true
effect give @s minecraft:instant_damage 1 0 true