#######
# Compiled from machines/compiler/compilation/modals.mcscript
# to error_location.mcfunction
#
# Generated by Minecraft Script for 1.13
######
data modify block ~ ~ ~ Items[{Slot:11b}].tag.compilation.error_page set value '[{"text":"  Page: ?", "bold": false, "italic": false, "color": "white"}]'
execute if data block ~ ~ ~ Items[{Slot:11b}].tag.compilation.error_path{page: 1} run data modify block ~ ~ ~ Items[{Slot:11b}].tag.compilation.error_page set value '[{"text":"    page: 1", "bold": false, "italic": true, "color": "white"}]'

execute if data block ~ ~ ~ Items[{Slot:11b}].tag.compilation.error_path{page: 2} run data modify block ~ ~ ~ Items[{Slot:11b}].tag.compilation.error_page set value '[{"text":"    page: 2", "bold": false, "italic": true, "color": "white"}]'

execute if data block ~ ~ ~ Items[{Slot:11b}].tag.compilation.error_path{page: 3} run data modify block ~ ~ ~ Items[{Slot:11b}].tag.compilation.error_page set value '[{"text":"    page: 3", "bold": false, "italic": true, "color": "white"}]'

execute if data block ~ ~ ~ Items[{Slot:11b}].tag.compilation.error_path{page: 4} run data modify block ~ ~ ~ Items[{Slot:11b}].tag.compilation.error_page set value '[{"text":"    page: 4", "bold": false, "italic": true, "color": "white"}]'

execute if data block ~ ~ ~ Items[{Slot:11b}].tag.compilation.error_path{page: 5} run data modify block ~ ~ ~ Items[{Slot:11b}].tag.compilation.error_page set value '[{"text":"    page: 5", "bold": false, "italic": true, "color": "white"}]'

execute if data block ~ ~ ~ Items[{Slot:11b}].tag.compilation.error_path{page: 6} run data modify block ~ ~ ~ Items[{Slot:11b}].tag.compilation.error_page set value '[{"text":"    page: 6", "bold": false, "italic": true, "color": "white"}]'

execute if data block ~ ~ ~ Items[{Slot:11b}].tag.compilation.error_path{page: 7} run data modify block ~ ~ ~ Items[{Slot:11b}].tag.compilation.error_page set value '[{"text":"    page: 7", "bold": false, "italic": true, "color": "white"}]'

execute if data block ~ ~ ~ Items[{Slot:11b}].tag.compilation.error_path{page: 8} run data modify block ~ ~ ~ Items[{Slot:11b}].tag.compilation.error_page set value '[{"text":"    page: 8", "bold": false, "italic": true, "color": "white"}]'

execute if data block ~ ~ ~ Items[{Slot:11b}].tag.compilation.error_path{page: 9} run data modify block ~ ~ ~ Items[{Slot:11b}].tag.compilation.error_page set value '[{"text":"    page: 9", "bold": false, "italic": true, "color": "white"}]'

execute if data block ~ ~ ~ Items[{Slot:11b}].tag.compilation.error_path{page: 10} run data modify block ~ ~ ~ Items[{Slot:11b}].tag.compilation.error_page set value '[{"text":"    page: 10", "bold": false, "italic": true, "color": "white"}]'

execute if data block ~ ~ ~ Items[{Slot:11b}].tag.compilation.error_path{page: 11} run data modify block ~ ~ ~ Items[{Slot:11b}].tag.compilation.error_page set value '[{"text":"    page: 11", "bold": false, "italic": true, "color": "white"}]'

execute if data block ~ ~ ~ Items[{Slot:11b}].tag.compilation.error_path{page: 12} run data modify block ~ ~ ~ Items[{Slot:11b}].tag.compilation.error_page set value '[{"text":"    page: 12", "bold": false, "italic": true, "color": "white"}]'

execute if data block ~ ~ ~ Items[{Slot:11b}].tag.compilation.error_path{page: 13} run data modify block ~ ~ ~ Items[{Slot:11b}].tag.compilation.error_page set value '[{"text":"    page: 13", "bold": false, "italic": true, "color": "white"}]'

execute if data block ~ ~ ~ Items[{Slot:11b}].tag.compilation.error_path{page: 14} run data modify block ~ ~ ~ Items[{Slot:11b}].tag.compilation.error_page set value '[{"text":"    page: 14", "bold": false, "italic": true, "color": "white"}]'

execute if data block ~ ~ ~ Items[{Slot:11b}].tag.compilation.error_path{page: 15} run data modify block ~ ~ ~ Items[{Slot:11b}].tag.compilation.error_page set value '[{"text":"    page: 15", "bold": false, "italic": true, "color": "white"}]'

execute if data block ~ ~ ~ Items[{Slot:11b}].tag.compilation.error_path{page: 16} run data modify block ~ ~ ~ Items[{Slot:11b}].tag.compilation.error_page set value '[{"text":"    page: 16", "bold": false, "italic": true, "color": "white"}]'

execute if data block ~ ~ ~ Items[{Slot:11b}].tag.compilation.error_path{page: 17} run data modify block ~ ~ ~ Items[{Slot:11b}].tag.compilation.error_page set value '[{"text":"    page: 17", "bold": false, "italic": true, "color": "white"}]'

execute if data block ~ ~ ~ Items[{Slot:11b}].tag.compilation.error_path{page: 18} run data modify block ~ ~ ~ Items[{Slot:11b}].tag.compilation.error_page set value '[{"text":"    page: 18", "bold": false, "italic": true, "color": "white"}]'

execute if data block ~ ~ ~ Items[{Slot:11b}].tag.compilation.error_path{page: 19} run data modify block ~ ~ ~ Items[{Slot:11b}].tag.compilation.error_page set value '[{"text":"    page: 19", "bold": false, "italic": true, "color": "white"}]'

execute if data block ~ ~ ~ Items[{Slot:11b}].tag.compilation.error_path{page: 20} run data modify block ~ ~ ~ Items[{Slot:11b}].tag.compilation.error_page set value '[{"text":"    page: 20", "bold": false, "italic": true, "color": "white"}]'

execute if data block ~ ~ ~ Items[{Slot:11b}].tag.compilation.error_path{page: 21} run data modify block ~ ~ ~ Items[{Slot:11b}].tag.compilation.error_page set value '[{"text":"    page: 21", "bold": false, "italic": true, "color": "white"}]'

execute if data block ~ ~ ~ Items[{Slot:11b}].tag.compilation.error_path{page: 22} run data modify block ~ ~ ~ Items[{Slot:11b}].tag.compilation.error_page set value '[{"text":"    page: 22", "bold": false, "italic": true, "color": "white"}]'

execute if data block ~ ~ ~ Items[{Slot:11b}].tag.compilation.error_path{page: 23} run data modify block ~ ~ ~ Items[{Slot:11b}].tag.compilation.error_page set value '[{"text":"    page: 23", "bold": false, "italic": true, "color": "white"}]'

execute if data block ~ ~ ~ Items[{Slot:11b}].tag.compilation.error_path{page: 24} run data modify block ~ ~ ~ Items[{Slot:11b}].tag.compilation.error_page set value '[{"text":"    page: 24", "bold": false, "italic": true, "color": "white"}]'

execute if data block ~ ~ ~ Items[{Slot:11b}].tag.compilation.error_path{page: 25} run data modify block ~ ~ ~ Items[{Slot:11b}].tag.compilation.error_page set value '[{"text":"    page: 25", "bold": false, "italic": true, "color": "white"}]'

execute if data block ~ ~ ~ Items[{Slot:11b}].tag.compilation.error_path{page: 26} run data modify block ~ ~ ~ Items[{Slot:11b}].tag.compilation.error_page set value '[{"text":"    page: 26", "bold": false, "italic": true, "color": "white"}]'

execute if data block ~ ~ ~ Items[{Slot:11b}].tag.compilation.error_path{page: 27} run data modify block ~ ~ ~ Items[{Slot:11b}].tag.compilation.error_page set value '[{"text":"    page: 27", "bold": false, "italic": true, "color": "white"}]'

execute if data block ~ ~ ~ Items[{Slot:11b}].tag.compilation.error_path{page: 28} run data modify block ~ ~ ~ Items[{Slot:11b}].tag.compilation.error_page set value '[{"text":"    page: 28", "bold": false, "italic": true, "color": "white"}]'

execute if data block ~ ~ ~ Items[{Slot:11b}].tag.compilation.error_path{page: 29} run data modify block ~ ~ ~ Items[{Slot:11b}].tag.compilation.error_page set value '[{"text":"    page: 29", "bold": false, "italic": true, "color": "white"}]'

execute if data block ~ ~ ~ Items[{Slot:11b}].tag.compilation.error_path{page: 30} run data modify block ~ ~ ~ Items[{Slot:11b}].tag.compilation.error_page set value '[{"text":"    page: 30", "bold": false, "italic": true, "color": "white"}]'

execute if data block ~ ~ ~ Items[{Slot:11b}].tag.compilation.error_path{page: 31} run data modify block ~ ~ ~ Items[{Slot:11b}].tag.compilation.error_page set value '[{"text":"    page: 31", "bold": false, "italic": true, "color": "white"}]'

execute if data block ~ ~ ~ Items[{Slot:11b}].tag.compilation.error_path{page: 32} run data modify block ~ ~ ~ Items[{Slot:11b}].tag.compilation.error_page set value '[{"text":"    page: 32", "bold": false, "italic": true, "color": "white"}]'

execute if data block ~ ~ ~ Items[{Slot:11b}].tag.compilation.error_path{page: 33} run data modify block ~ ~ ~ Items[{Slot:11b}].tag.compilation.error_page set value '[{"text":"    page: 33", "bold": false, "italic": true, "color": "white"}]'

execute if data block ~ ~ ~ Items[{Slot:11b}].tag.compilation.error_path{page: 34} run data modify block ~ ~ ~ Items[{Slot:11b}].tag.compilation.error_page set value '[{"text":"    page: 34", "bold": false, "italic": true, "color": "white"}]'

execute if data block ~ ~ ~ Items[{Slot:11b}].tag.compilation.error_path{page: 35} run data modify block ~ ~ ~ Items[{Slot:11b}].tag.compilation.error_page set value '[{"text":"    page: 35", "bold": false, "italic": true, "color": "white"}]'

execute if data block ~ ~ ~ Items[{Slot:11b}].tag.compilation.error_path{page: 36} run data modify block ~ ~ ~ Items[{Slot:11b}].tag.compilation.error_page set value '[{"text":"    page: 36", "bold": false, "italic": true, "color": "white"}]'

execute if data block ~ ~ ~ Items[{Slot:11b}].tag.compilation.error_path{page: 37} run data modify block ~ ~ ~ Items[{Slot:11b}].tag.compilation.error_page set value '[{"text":"    page: 37", "bold": false, "italic": true, "color": "white"}]'

execute if data block ~ ~ ~ Items[{Slot:11b}].tag.compilation.error_path{page: 38} run data modify block ~ ~ ~ Items[{Slot:11b}].tag.compilation.error_page set value '[{"text":"    page: 38", "bold": false, "italic": true, "color": "white"}]'

execute if data block ~ ~ ~ Items[{Slot:11b}].tag.compilation.error_path{page: 39} run data modify block ~ ~ ~ Items[{Slot:11b}].tag.compilation.error_page set value '[{"text":"    page: 39", "bold": false, "italic": true, "color": "white"}]'

execute if data block ~ ~ ~ Items[{Slot:11b}].tag.compilation.error_path{page: 40} run data modify block ~ ~ ~ Items[{Slot:11b}].tag.compilation.error_page set value '[{"text":"    page: 40", "bold": false, "italic": true, "color": "white"}]'

execute if data block ~ ~ ~ Items[{Slot:11b}].tag.compilation.error_path{page: 41} run data modify block ~ ~ ~ Items[{Slot:11b}].tag.compilation.error_page set value '[{"text":"    page: 41", "bold": false, "italic": true, "color": "white"}]'

execute if data block ~ ~ ~ Items[{Slot:11b}].tag.compilation.error_path{page: 42} run data modify block ~ ~ ~ Items[{Slot:11b}].tag.compilation.error_page set value '[{"text":"    page: 42", "bold": false, "italic": true, "color": "white"}]'

execute if data block ~ ~ ~ Items[{Slot:11b}].tag.compilation.error_path{page: 43} run data modify block ~ ~ ~ Items[{Slot:11b}].tag.compilation.error_page set value '[{"text":"    page: 43", "bold": false, "italic": true, "color": "white"}]'

execute if data block ~ ~ ~ Items[{Slot:11b}].tag.compilation.error_path{page: 44} run data modify block ~ ~ ~ Items[{Slot:11b}].tag.compilation.error_page set value '[{"text":"    page: 44", "bold": false, "italic": true, "color": "white"}]'

execute if data block ~ ~ ~ Items[{Slot:11b}].tag.compilation.error_path{page: 45} run data modify block ~ ~ ~ Items[{Slot:11b}].tag.compilation.error_page set value '[{"text":"    page: 45", "bold": false, "italic": true, "color": "white"}]'

execute if data block ~ ~ ~ Items[{Slot:11b}].tag.compilation.error_path{page: 46} run data modify block ~ ~ ~ Items[{Slot:11b}].tag.compilation.error_page set value '[{"text":"    page: 46", "bold": false, "italic": true, "color": "white"}]'

execute if data block ~ ~ ~ Items[{Slot:11b}].tag.compilation.error_path{page: 47} run data modify block ~ ~ ~ Items[{Slot:11b}].tag.compilation.error_page set value '[{"text":"    page: 47", "bold": false, "italic": true, "color": "white"}]'

execute if data block ~ ~ ~ Items[{Slot:11b}].tag.compilation.error_path{page: 48} run data modify block ~ ~ ~ Items[{Slot:11b}].tag.compilation.error_page set value '[{"text":"    page: 48", "bold": false, "italic": true, "color": "white"}]'

execute if data block ~ ~ ~ Items[{Slot:11b}].tag.compilation.error_path{page: 49} run data modify block ~ ~ ~ Items[{Slot:11b}].tag.compilation.error_page set value '[{"text":"    page: 49", "bold": false, "italic": true, "color": "white"}]'

execute if data block ~ ~ ~ Items[{Slot:11b}].tag.compilation.error_path{page: 50} run data modify block ~ ~ ~ Items[{Slot:11b}].tag.compilation.error_page set value '[{"text":"    page: 50", "bold": false, "italic": true, "color": "white"}]'

execute if data block ~ ~ ~ Items[{Slot:11b}].tag.compilation.error_path{slot: 0} run data modify block ~ ~ ~ Items[{Slot:11b}].tag.compilation.error_row set value '[{"text":"    line: 1", "bold": false, "italic": true, "color": "white"}]'
execute if data block ~ ~ ~ Items[{Slot:11b}].tag.compilation.error_path{slot: 0} run data modify block ~ ~ ~ Items[{Slot:11b}].tag.compilation.error_col set value '[{"text":"    col:  1", "bold": false, "italic": true, "color": "white"}]'

execute if data block ~ ~ ~ Items[{Slot:11b}].tag.compilation.error_path{slot: 1} run data modify block ~ ~ ~ Items[{Slot:11b}].tag.compilation.error_row set value '[{"text":"    line: 1", "bold": false, "italic": true, "color": "white"}]'
execute if data block ~ ~ ~ Items[{Slot:11b}].tag.compilation.error_path{slot: 1} run data modify block ~ ~ ~ Items[{Slot:11b}].tag.compilation.error_col set value '[{"text":"    col:  2", "bold": false, "italic": true, "color": "white"}]'

execute if data block ~ ~ ~ Items[{Slot:11b}].tag.compilation.error_path{slot: 2} run data modify block ~ ~ ~ Items[{Slot:11b}].tag.compilation.error_row set value '[{"text":"    line: 1", "bold": false, "italic": true, "color": "white"}]'
execute if data block ~ ~ ~ Items[{Slot:11b}].tag.compilation.error_path{slot: 2} run data modify block ~ ~ ~ Items[{Slot:11b}].tag.compilation.error_col set value '[{"text":"    col:  3", "bold": false, "italic": true, "color": "white"}]'

execute if data block ~ ~ ~ Items[{Slot:11b}].tag.compilation.error_path{slot: 3} run data modify block ~ ~ ~ Items[{Slot:11b}].tag.compilation.error_row set value '[{"text":"    line: 1", "bold": false, "italic": true, "color": "white"}]'
execute if data block ~ ~ ~ Items[{Slot:11b}].tag.compilation.error_path{slot: 3} run data modify block ~ ~ ~ Items[{Slot:11b}].tag.compilation.error_col set value '[{"text":"    col:  4", "bold": false, "italic": true, "color": "white"}]'

execute if data block ~ ~ ~ Items[{Slot:11b}].tag.compilation.error_path{slot: 4} run data modify block ~ ~ ~ Items[{Slot:11b}].tag.compilation.error_row set value '[{"text":"    line: 1", "bold": false, "italic": true, "color": "white"}]'
execute if data block ~ ~ ~ Items[{Slot:11b}].tag.compilation.error_path{slot: 4} run data modify block ~ ~ ~ Items[{Slot:11b}].tag.compilation.error_col set value '[{"text":"    col:  5", "bold": false, "italic": true, "color": "white"}]'

execute if data block ~ ~ ~ Items[{Slot:11b}].tag.compilation.error_path{slot: 5} run data modify block ~ ~ ~ Items[{Slot:11b}].tag.compilation.error_row set value '[{"text":"    line: 1", "bold": false, "italic": true, "color": "white"}]'
execute if data block ~ ~ ~ Items[{Slot:11b}].tag.compilation.error_path{slot: 5} run data modify block ~ ~ ~ Items[{Slot:11b}].tag.compilation.error_col set value '[{"text":"    col:  6", "bold": false, "italic": true, "color": "white"}]'

execute if data block ~ ~ ~ Items[{Slot:11b}].tag.compilation.error_path{slot: 6} run data modify block ~ ~ ~ Items[{Slot:11b}].tag.compilation.error_row set value '[{"text":"    line: 1", "bold": false, "italic": true, "color": "white"}]'
execute if data block ~ ~ ~ Items[{Slot:11b}].tag.compilation.error_path{slot: 6} run data modify block ~ ~ ~ Items[{Slot:11b}].tag.compilation.error_col set value '[{"text":"    col:  7", "bold": false, "italic": true, "color": "white"}]'

execute if data block ~ ~ ~ Items[{Slot:11b}].tag.compilation.error_path{slot: 7} run data modify block ~ ~ ~ Items[{Slot:11b}].tag.compilation.error_row set value '[{"text":"    line: 1", "bold": false, "italic": true, "color": "white"}]'
execute if data block ~ ~ ~ Items[{Slot:11b}].tag.compilation.error_path{slot: 7} run data modify block ~ ~ ~ Items[{Slot:11b}].tag.compilation.error_col set value '[{"text":"    col:  8", "bold": false, "italic": true, "color": "white"}]'

execute if data block ~ ~ ~ Items[{Slot:11b}].tag.compilation.error_path{slot: 9} run data modify block ~ ~ ~ Items[{Slot:11b}].tag.compilation.error_row set value '[{"text":"    line: 2", "bold": false, "italic": true, "color": "white"}]'
execute if data block ~ ~ ~ Items[{Slot:11b}].tag.compilation.error_path{slot: 9} run data modify block ~ ~ ~ Items[{Slot:11b}].tag.compilation.error_col set value '[{"text":"    col:  1", "bold": false, "italic": true, "color": "white"}]'

execute if data block ~ ~ ~ Items[{Slot:11b}].tag.compilation.error_path{slot: 10} run data modify block ~ ~ ~ Items[{Slot:11b}].tag.compilation.error_row set value '[{"text":"    line: 2", "bold": false, "italic": true, "color": "white"}]'
execute if data block ~ ~ ~ Items[{Slot:11b}].tag.compilation.error_path{slot: 10} run data modify block ~ ~ ~ Items[{Slot:11b}].tag.compilation.error_col set value '[{"text":"    col:  2", "bold": false, "italic": true, "color": "white"}]'

execute if data block ~ ~ ~ Items[{Slot:11b}].tag.compilation.error_path{slot: 11} run data modify block ~ ~ ~ Items[{Slot:11b}].tag.compilation.error_row set value '[{"text":"    line: 2", "bold": false, "italic": true, "color": "white"}]'
execute if data block ~ ~ ~ Items[{Slot:11b}].tag.compilation.error_path{slot: 11} run data modify block ~ ~ ~ Items[{Slot:11b}].tag.compilation.error_col set value '[{"text":"    col:  3", "bold": false, "italic": true, "color": "white"}]'

execute if data block ~ ~ ~ Items[{Slot:11b}].tag.compilation.error_path{slot: 12} run data modify block ~ ~ ~ Items[{Slot:11b}].tag.compilation.error_row set value '[{"text":"    line: 2", "bold": false, "italic": true, "color": "white"}]'
execute if data block ~ ~ ~ Items[{Slot:11b}].tag.compilation.error_path{slot: 12} run data modify block ~ ~ ~ Items[{Slot:11b}].tag.compilation.error_col set value '[{"text":"    col:  4", "bold": false, "italic": true, "color": "white"}]'

execute if data block ~ ~ ~ Items[{Slot:11b}].tag.compilation.error_path{slot: 13} run data modify block ~ ~ ~ Items[{Slot:11b}].tag.compilation.error_row set value '[{"text":"    line: 2", "bold": false, "italic": true, "color": "white"}]'
execute if data block ~ ~ ~ Items[{Slot:11b}].tag.compilation.error_path{slot: 13} run data modify block ~ ~ ~ Items[{Slot:11b}].tag.compilation.error_col set value '[{"text":"    col:  5", "bold": false, "italic": true, "color": "white"}]'

execute if data block ~ ~ ~ Items[{Slot:11b}].tag.compilation.error_path{slot: 14} run data modify block ~ ~ ~ Items[{Slot:11b}].tag.compilation.error_row set value '[{"text":"    line: 2", "bold": false, "italic": true, "color": "white"}]'
execute if data block ~ ~ ~ Items[{Slot:11b}].tag.compilation.error_path{slot: 14} run data modify block ~ ~ ~ Items[{Slot:11b}].tag.compilation.error_col set value '[{"text":"    col:  6", "bold": false, "italic": true, "color": "white"}]'

execute if data block ~ ~ ~ Items[{Slot:11b}].tag.compilation.error_path{slot: 15} run data modify block ~ ~ ~ Items[{Slot:11b}].tag.compilation.error_row set value '[{"text":"    line: 2", "bold": false, "italic": true, "color": "white"}]'
execute if data block ~ ~ ~ Items[{Slot:11b}].tag.compilation.error_path{slot: 15} run data modify block ~ ~ ~ Items[{Slot:11b}].tag.compilation.error_col set value '[{"text":"    col:  7", "bold": false, "italic": true, "color": "white"}]'

execute if data block ~ ~ ~ Items[{Slot:11b}].tag.compilation.error_path{slot: 16} run data modify block ~ ~ ~ Items[{Slot:11b}].tag.compilation.error_row set value '[{"text":"    line: 2", "bold": false, "italic": true, "color": "white"}]'
execute if data block ~ ~ ~ Items[{Slot:11b}].tag.compilation.error_path{slot: 16} run data modify block ~ ~ ~ Items[{Slot:11b}].tag.compilation.error_col set value '[{"text":"    col:  8", "bold": false, "italic": true, "color": "white"}]'

execute if data block ~ ~ ~ Items[{Slot:11b}].tag.compilation.error_path{slot: 18} run data modify block ~ ~ ~ Items[{Slot:11b}].tag.compilation.error_row set value '[{"text":"    line: 3", "bold": false, "italic": true, "color": "white"}]'
execute if data block ~ ~ ~ Items[{Slot:11b}].tag.compilation.error_path{slot: 18} run data modify block ~ ~ ~ Items[{Slot:11b}].tag.compilation.error_col set value '[{"text":"    col:  1", "bold": false, "italic": true, "color": "white"}]'

execute if data block ~ ~ ~ Items[{Slot:11b}].tag.compilation.error_path{slot: 19} run data modify block ~ ~ ~ Items[{Slot:11b}].tag.compilation.error_row set value '[{"text":"    line: 3", "bold": false, "italic": true, "color": "white"}]'
execute if data block ~ ~ ~ Items[{Slot:11b}].tag.compilation.error_path{slot: 19} run data modify block ~ ~ ~ Items[{Slot:11b}].tag.compilation.error_col set value '[{"text":"    col:  2", "bold": false, "italic": true, "color": "white"}]'

execute if data block ~ ~ ~ Items[{Slot:11b}].tag.compilation.error_path{slot: 20} run data modify block ~ ~ ~ Items[{Slot:11b}].tag.compilation.error_row set value '[{"text":"    line: 3", "bold": false, "italic": true, "color": "white"}]'
execute if data block ~ ~ ~ Items[{Slot:11b}].tag.compilation.error_path{slot: 20} run data modify block ~ ~ ~ Items[{Slot:11b}].tag.compilation.error_col set value '[{"text":"    col:  3", "bold": false, "italic": true, "color": "white"}]'

execute if data block ~ ~ ~ Items[{Slot:11b}].tag.compilation.error_path{slot: 21} run data modify block ~ ~ ~ Items[{Slot:11b}].tag.compilation.error_row set value '[{"text":"    line: 3", "bold": false, "italic": true, "color": "white"}]'
execute if data block ~ ~ ~ Items[{Slot:11b}].tag.compilation.error_path{slot: 21} run data modify block ~ ~ ~ Items[{Slot:11b}].tag.compilation.error_col set value '[{"text":"    col:  4", "bold": false, "italic": true, "color": "white"}]'

execute if data block ~ ~ ~ Items[{Slot:11b}].tag.compilation.error_path{slot: 22} run data modify block ~ ~ ~ Items[{Slot:11b}].tag.compilation.error_row set value '[{"text":"    line: 3", "bold": false, "italic": true, "color": "white"}]'
execute if data block ~ ~ ~ Items[{Slot:11b}].tag.compilation.error_path{slot: 22} run data modify block ~ ~ ~ Items[{Slot:11b}].tag.compilation.error_col set value '[{"text":"    col:  5", "bold": false, "italic": true, "color": "white"}]'

execute if data block ~ ~ ~ Items[{Slot:11b}].tag.compilation.error_path{slot: 23} run data modify block ~ ~ ~ Items[{Slot:11b}].tag.compilation.error_row set value '[{"text":"    line: 3", "bold": false, "italic": true, "color": "white"}]'
execute if data block ~ ~ ~ Items[{Slot:11b}].tag.compilation.error_path{slot: 23} run data modify block ~ ~ ~ Items[{Slot:11b}].tag.compilation.error_col set value '[{"text":"    col:  6", "bold": false, "italic": true, "color": "white"}]'

execute if data block ~ ~ ~ Items[{Slot:11b}].tag.compilation.error_path{slot: 24} run data modify block ~ ~ ~ Items[{Slot:11b}].tag.compilation.error_row set value '[{"text":"    line: 3", "bold": false, "italic": true, "color": "white"}]'
execute if data block ~ ~ ~ Items[{Slot:11b}].tag.compilation.error_path{slot: 24} run data modify block ~ ~ ~ Items[{Slot:11b}].tag.compilation.error_col set value '[{"text":"    col:  7", "bold": false, "italic": true, "color": "white"}]'

execute if data block ~ ~ ~ Items[{Slot:11b}].tag.compilation.error_path{slot: 25} run data modify block ~ ~ ~ Items[{Slot:11b}].tag.compilation.error_row set value '[{"text":"    line: 3", "bold": false, "italic": true, "color": "white"}]'
execute if data block ~ ~ ~ Items[{Slot:11b}].tag.compilation.error_path{slot: 25} run data modify block ~ ~ ~ Items[{Slot:11b}].tag.compilation.error_col set value '[{"text":"    col:  8", "bold": false, "italic": true, "color": "white"}]'
