#######
# Compiled from data/computercraft_crafting/functions/main.mcscript
# to .//data/computercraft_crafting/functions/creations/5.mcfunction
#
# Generated by Minecraft Script for 1.13
######
setblock ~ ~ ~ minecraft:player_head
execute if entity @s[y_rotation=-45..44.99] run summon armor_stand ~0.5 ~0.5 ~0.5 {Tags: [isCustomBlock,block5,newBlock],CustomName:'{"text":"Wireless link"}',Invisible:1,Marker:1,NoGravity:1,Rotation:[180f,0f]}
execute if entity @s[y_rotation=45..134.99] run summon armor_stand ~0.5 ~0.5 ~0.5 {Tags: [isCustomBlock,block5,newBlock],CustomName:'{"text":"Wireless link"}',Invisible:1,Marker:1,NoGravity:1,Rotation:[-90f,0f]}
execute if entity @s[y_rotation=135..-135.01] run summon armor_stand ~0.5 ~0.5 ~0.5 {Tags: [isCustomBlock,block5,newBlock],CustomName:'{"text":"Wireless link"}',Invisible:1,Marker:1,NoGravity:1,Rotation:[0f,0f]}
execute if entity @s[y_rotation=-135..-45] run summon armor_stand ~0.5 ~0.5 ~0.5 {Tags: [isCustomBlock,block5,newBlock],CustomName:'{"text":"Wireless link"}',Invisible:1,Marker:1,NoGravity:1,Rotation:[90f,0f]}
execute as @e[tag=block5,tag=newBlock] run replaceitem entity @s armor.head minecraft:firework_rocket{CustomModelData:24007}
execute as @e[tag=block5,tag=newBlock] run data merge entity @s {Fire:23000s}
execute as @e[tag=block5,tag=newBlock] run tag @s remove newBlock
