#######
# Compiled from data/computercraft_crafting/functions/main.mcscript
# to .//data/computercraft_crafting/functions/break/1.mcfunction
#
# Generated by Minecraft Script for 1.13
######
kill @e[type=item,distance=..0.8]
function computercraft_crafting:printer_return_paper
summon minecraft:item ~ ~0.5 ~ {Item:{id:"minecraft:firework_rocket",Count:1,tag:{CustomModelData:24003,display:{Name:"[{\"text\":\"Printer\",\"italic\":false}]"},computercraft_craftingBlock:1,Fireworks:{}}}}
kill @s
