#######
# Compiled from data/computercraft_crafting/functions/main.mcscript
# to .//data/computercraft_crafting/functions/break/4.mcfunction
#
# Generated by Minecraft Script for 1.13
######
kill @e[type=item,distance=..0.8,nbt={Item:{tag:{CustomModelData:24101}}}]
kill @e[type=item,distance=..0.8,nbt={Item:{tag:{CustomModelData:24102}}}]
kill @e[type=item,distance=..0.8,nbt={Item:{tag:{CustomModelData:24103}}}]
kill @e[type=item,distance=..0.8,nbt={Item:{tag:{CustomModelData:24104}}}]
kill @e[type=item,distance=..0.8,nbt={Item:{tag:{CustomModelData:24105}}}]
kill @e[type=item,distance=..0.8,nbt={Item:{tag:{CustomModelData:24106}}}]
kill @e[type=item,distance=..0.8,nbt={Item:{tag:{CustomModelData:24107}}}]
kill @e[type=item,distance=..0.8,nbt={Item:{tag:{CustomModelData:24108}}}]
kill @e[type=item,distance=..0.8,nbt={Item:{tag:{CustomModelData:24109}}}]
kill @e[type=item,distance=..0.8,nbt={Item:{tag:{CustomModelData:24110}}}]
summon minecraft:item ~ ~0.5 ~ {Item:{id:"minecraft:firework_rocket",Count:1,tag:{CustomModelData:24006,display:{Name:"[{\"text\":\"Compiler\",\"italic\":false}]"},computercraft_craftingBlock:4,Fireworks:{}}}}
kill @s