#######
# Compiled from data/computercraft/functions/crafting.mcscript
# to .//data/computercraft/functions/crafting.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute as @a[nbt={Inventory:[{id:"minecraft:knowledge_book"}]}] run tag @s add CC_CraftBlock
execute as @a[tag=CC_CraftBlock] at @s run clear @s knowledge_book 1
execute as @a[tag=CC_CraftBlock] at @s run give @s minecraft:firework_rocket{CustomModelData:24004,computercraft_craftingBlock:2,display:{Name:"[{\"text\":\"Assembler\",\"italic\":false}]"}} 1
execute as @a[tag=CC_CraftBlock] at @s run tag @s remove CC_CraftBlock