#######
# Compiled from data/computercraft/functions/load.mcscript
# to .//data/computercraft/functions/load.mcfunction
#
# Generated by Minecraft Script for 1.13
######
function computercraft:mcscript/load

scoreboard objectives add currentRotation dummy
scoreboard objectives add robotId dummy
scoreboard objectives add paper dummy
scoreboard objectives add temp dummy
scoreboard objectives add temp2 dummy
scoreboard objectives add recipe dummy
scoreboard objectives add scroll dummy
scoreboard objectives add gameTicks dummy
scoreboard players set CC gameTicks 0
scoreboard objectives add currentRobotId dummy
scoreboard players set CC currentRobotId 1
scoreboard objectives add ticksPerCommand dummy
scoreboard players set CC ticksPerCommand 5
scoreboard objectives add maxCommands dummy
scoreboard players set CC maxCommands 27
scoreboard objectives add maxAngle dummy
scoreboard players set CC maxAngle 360