#######
# Compiled from data/computercraft/functions/main.mcscript
# to .//data/computercraft/functions/main.mcfunction
#
# Generated by Minecraft Script for 1.13
######
scoreboard players add CC gameTicks 1
scoreboard players operation CC gameTicks %= CC ticksPerCommand
function computercraft:crafting
function computercraft:machines/main