#######
# Compiled from computercraft/functions/machines/gui.mcscript
# to .//data/computercraft/functions/machines/gui.mcfunction
#
# Generated by Minecraft Script for 1.13
######
clear @a minecraft:paper{CustomModelData:24101}
clear @a minecraft:paper{CustomModelData:24102}
clear @a minecraft:paper{CustomModelData:24103}
clear @a minecraft:paper{CustomModelData:24104}
clear @a minecraft:paper{CustomModelData:24105}
clear @a minecraft:paper{CustomModelData:24106}
clear @a minecraft:paper{CustomModelData:24107}
clear @a minecraft:paper{CustomModelData:24108}
clear @a minecraft:paper{CustomModelData:24109}
clear @a minecraft:paper{CustomModelData:24110}