#######
# Compiled from computercraft/functions/machines/main.mcscript
# to .//data/computercraft/functions/machines/main.mcfunction
#
# Generated by Minecraft Script for 1.13
######
function computercraft:machines/printer
function computercraft:machines/assembler
function computercraft:machines/programmer
function computercraft:machines/compiler/main
function computercraft:machines/robot/main
function computercraft:machines/gui