#######
# Compiled from machines/compiler/compilation/00_copy.mcscript
# to .//data/computercraft/functions/machines/compiler/compilation/00.mcfunction
#
# Generated by Minecraft Script for 1.13
######
data modify block ~ ~ ~ Items[{Slot:11b}].tag.compilation.source set value []
data modify block ~ ~ ~ Items[{Slot:11b}].tag.compilation.source append from block ~ ~ ~ Items[{Slot:11b}].tag.code.1
data modify block ~ ~ ~ Items[{Slot:11b}].tag.compilation.source append from block ~ ~ ~ Items[{Slot:11b}].tag.code.2
data modify block ~ ~ ~ Items[{Slot:11b}].tag.compilation.source append from block ~ ~ ~ Items[{Slot:11b}].tag.code.3
data modify block ~ ~ ~ Items[{Slot:11b}].tag.compilation.source append from block ~ ~ ~ Items[{Slot:11b}].tag.code.4
data modify block ~ ~ ~ Items[{Slot:11b}].tag.compilation.source append from block ~ ~ ~ Items[{Slot:11b}].tag.code.5
data modify block ~ ~ ~ Items[{Slot:11b}].tag.compilation.source append from block ~ ~ ~ Items[{Slot:11b}].tag.code.6
data modify block ~ ~ ~ Items[{Slot:11b}].tag.compilation.source append from block ~ ~ ~ Items[{Slot:11b}].tag.code.7
data modify block ~ ~ ~ Items[{Slot:11b}].tag.compilation.source append from block ~ ~ ~ Items[{Slot:11b}].tag.code.8
data modify block ~ ~ ~ Items[{Slot:11b}].tag.compilation.source append from block ~ ~ ~ Items[{Slot:11b}].tag.code.9
data modify block ~ ~ ~ Items[{Slot:11b}].tag.compilation.source append from block ~ ~ ~ Items[{Slot:11b}].tag.code.10
data modify block ~ ~ ~ Items[{Slot:11b}].tag.compilation.source append from block ~ ~ ~ Items[{Slot:11b}].tag.code.11
data modify block ~ ~ ~ Items[{Slot:11b}].tag.compilation.source append from block ~ ~ ~ Items[{Slot:11b}].tag.code.12
data modify block ~ ~ ~ Items[{Slot:11b}].tag.compilation.source append from block ~ ~ ~ Items[{Slot:11b}].tag.code.13
data modify block ~ ~ ~ Items[{Slot:11b}].tag.compilation.source append from block ~ ~ ~ Items[{Slot:11b}].tag.code.14
data modify block ~ ~ ~ Items[{Slot:11b}].tag.compilation.source append from block ~ ~ ~ Items[{Slot:11b}].tag.code.15
data modify block ~ ~ ~ Items[{Slot:11b}].tag.compilation.source append from block ~ ~ ~ Items[{Slot:11b}].tag.code.16
data modify block ~ ~ ~ Items[{Slot:11b}].tag.compilation.source append from block ~ ~ ~ Items[{Slot:11b}].tag.code.17
data modify block ~ ~ ~ Items[{Slot:11b}].tag.compilation.source append from block ~ ~ ~ Items[{Slot:11b}].tag.code.18
data modify block ~ ~ ~ Items[{Slot:11b}].tag.compilation.source append from block ~ ~ ~ Items[{Slot:11b}].tag.code.19
data modify block ~ ~ ~ Items[{Slot:11b}].tag.compilation.source append from block ~ ~ ~ Items[{Slot:11b}].tag.code.20