#######
# Compiled from machines/compiler/compilation/00_copy.mcscript
# to .//data/computercraft/functions/machines/compiler/compilation/00.mcfunction
#
# Generated by Minecraft Script for 1.13
######
data modify block ~ ~ ~ Items[{Slot:11b}].tag.compilation.source set value []
data modify block ~ ~ ~ Items[{Slot:11b}].tag.compilation.source append from block ~ ~ ~ Items[{Slot:11b}].tag.code.1
data modify block ~ ~ ~ Items[{Slot:11b}].tag.compilation.source append from block ~ ~ ~ Items[{Slot:11b}].tag.code.2
data modify block ~ ~ ~ Items[{Slot:11b}].tag.compilation.source append from block ~ ~ ~ Items[{Slot:11b}].tag.code.3
data modify block ~ ~ ~ Items[{Slot:11b}].tag.compilation.source append from block ~ ~ ~ Items[{Slot:11b}].tag.code.4
data modify block ~ ~ ~ Items[{Slot:11b}].tag.compilation.source append from block ~ ~ ~ Items[{Slot:11b}].tag.code.5
data modify block ~ ~ ~ Items[{Slot:11b}].tag.compilation.source append from block ~ ~ ~ Items[{Slot:11b}].tag.code.6
data modify block ~ ~ ~ Items[{Slot:11b}].tag.compilation.source append from block ~ ~ ~ Items[{Slot:11b}].tag.code.7
data modify block ~ ~ ~ Items[{Slot:11b}].tag.compilation.source append from block ~ ~ ~ Items[{Slot:11b}].tag.code.8
data modify block ~ ~ ~ Items[{Slot:11b}].tag.compilation.source append from block ~ ~ ~ Items[{Slot:11b}].tag.code.9
data modify block ~ ~ ~ Items[{Slot:11b}].tag.compilation.source append from block ~ ~ ~ Items[{Slot:11b}].tag.code.10
data modify block ~ ~ ~ Items[{Slot:11b}].tag.compilation.source append from block ~ ~ ~ Items[{Slot:11b}].tag.code.11
data modify block ~ ~ ~ Items[{Slot:11b}].tag.compilation.source append from block ~ ~ ~ Items[{Slot:11b}].tag.code.12
data modify block ~ ~ ~ Items[{Slot:11b}].tag.compilation.source append from block ~ ~ ~ Items[{Slot:11b}].tag.code.13
data modify block ~ ~ ~ Items[{Slot:11b}].tag.compilation.source append from block ~ ~ ~ Items[{Slot:11b}].tag.code.14
data modify block ~ ~ ~ Items[{Slot:11b}].tag.compilation.source append from block ~ ~ ~ Items[{Slot:11b}].tag.code.15
data modify block ~ ~ ~ Items[{Slot:11b}].tag.compilation.source append from block ~ ~ ~ Items[{Slot:11b}].tag.code.16
data modify block ~ ~ ~ Items[{Slot:11b}].tag.compilation.source append from block ~ ~ ~ Items[{Slot:11b}].tag.code.17
data modify block ~ ~ ~ Items[{Slot:11b}].tag.compilation.source append from block ~ ~ ~ Items[{Slot:11b}].tag.code.18
data modify block ~ ~ ~ Items[{Slot:11b}].tag.compilation.source append from block ~ ~ ~ Items[{Slot:11b}].tag.code.19
data modify block ~ ~ ~ Items[{Slot:11b}].tag.compilation.source append from block ~ ~ ~ Items[{Slot:11b}].tag.code.20
data modify block ~ ~ ~ Items[{Slot:11b}].tag.compilation.source append from block ~ ~ ~ Items[{Slot:11b}].tag.code.21
data modify block ~ ~ ~ Items[{Slot:11b}].tag.compilation.source append from block ~ ~ ~ Items[{Slot:11b}].tag.code.22
data modify block ~ ~ ~ Items[{Slot:11b}].tag.compilation.source append from block ~ ~ ~ Items[{Slot:11b}].tag.code.23
data modify block ~ ~ ~ Items[{Slot:11b}].tag.compilation.source append from block ~ ~ ~ Items[{Slot:11b}].tag.code.24
data modify block ~ ~ ~ Items[{Slot:11b}].tag.compilation.source append from block ~ ~ ~ Items[{Slot:11b}].tag.code.25
data modify block ~ ~ ~ Items[{Slot:11b}].tag.compilation.source append from block ~ ~ ~ Items[{Slot:11b}].tag.code.26
data modify block ~ ~ ~ Items[{Slot:11b}].tag.compilation.source append from block ~ ~ ~ Items[{Slot:11b}].tag.code.27
data modify block ~ ~ ~ Items[{Slot:11b}].tag.compilation.source append from block ~ ~ ~ Items[{Slot:11b}].tag.code.28
data modify block ~ ~ ~ Items[{Slot:11b}].tag.compilation.source append from block ~ ~ ~ Items[{Slot:11b}].tag.code.29
data modify block ~ ~ ~ Items[{Slot:11b}].tag.compilation.source append from block ~ ~ ~ Items[{Slot:11b}].tag.code.30
data modify block ~ ~ ~ Items[{Slot:11b}].tag.compilation.source append from block ~ ~ ~ Items[{Slot:11b}].tag.code.31
data modify block ~ ~ ~ Items[{Slot:11b}].tag.compilation.source append from block ~ ~ ~ Items[{Slot:11b}].tag.code.32
data modify block ~ ~ ~ Items[{Slot:11b}].tag.compilation.source append from block ~ ~ ~ Items[{Slot:11b}].tag.code.33
data modify block ~ ~ ~ Items[{Slot:11b}].tag.compilation.source append from block ~ ~ ~ Items[{Slot:11b}].tag.code.34
data modify block ~ ~ ~ Items[{Slot:11b}].tag.compilation.source append from block ~ ~ ~ Items[{Slot:11b}].tag.code.35
data modify block ~ ~ ~ Items[{Slot:11b}].tag.compilation.source append from block ~ ~ ~ Items[{Slot:11b}].tag.code.36
data modify block ~ ~ ~ Items[{Slot:11b}].tag.compilation.source append from block ~ ~ ~ Items[{Slot:11b}].tag.code.37
data modify block ~ ~ ~ Items[{Slot:11b}].tag.compilation.source append from block ~ ~ ~ Items[{Slot:11b}].tag.code.38
data modify block ~ ~ ~ Items[{Slot:11b}].tag.compilation.source append from block ~ ~ ~ Items[{Slot:11b}].tag.code.39
data modify block ~ ~ ~ Items[{Slot:11b}].tag.compilation.source append from block ~ ~ ~ Items[{Slot:11b}].tag.code.40
data modify block ~ ~ ~ Items[{Slot:11b}].tag.compilation.source append from block ~ ~ ~ Items[{Slot:11b}].tag.code.41
data modify block ~ ~ ~ Items[{Slot:11b}].tag.compilation.source append from block ~ ~ ~ Items[{Slot:11b}].tag.code.42
data modify block ~ ~ ~ Items[{Slot:11b}].tag.compilation.source append from block ~ ~ ~ Items[{Slot:11b}].tag.code.43
data modify block ~ ~ ~ Items[{Slot:11b}].tag.compilation.source append from block ~ ~ ~ Items[{Slot:11b}].tag.code.44
data modify block ~ ~ ~ Items[{Slot:11b}].tag.compilation.source append from block ~ ~ ~ Items[{Slot:11b}].tag.code.45
data modify block ~ ~ ~ Items[{Slot:11b}].tag.compilation.source append from block ~ ~ ~ Items[{Slot:11b}].tag.code.46
data modify block ~ ~ ~ Items[{Slot:11b}].tag.compilation.source append from block ~ ~ ~ Items[{Slot:11b}].tag.code.47
data modify block ~ ~ ~ Items[{Slot:11b}].tag.compilation.source append from block ~ ~ ~ Items[{Slot:11b}].tag.code.48
data modify block ~ ~ ~ Items[{Slot:11b}].tag.compilation.source append from block ~ ~ ~ Items[{Slot:11b}].tag.code.49
data modify block ~ ~ ~ Items[{Slot:11b}].tag.compilation.source append from block ~ ~ ~ Items[{Slot:11b}].tag.code.50