#######
# Compiled from machines/compiler/compilation/02_translating.mcscript
# to .//data/computercraft/functions/machines/compiler/compilation/02.mcfunction
#
# Generated by Minecraft Script for 1.13
######
data modify block ~ ~ ~ Items[{Slot:11b}].tag.compilation.temp_read set from block ~ ~ ~ Items[{Slot:11b}].tag.compilation.merged[0]
data modify block ~ ~ ~ Items[{Slot:11b}].tag.compilation.temp_write set value {type: 0}
data modify block ~ ~ ~ Items[{Slot:11b}].tag.compilation.temp_write.id set from block ~ ~ ~ Items[{Slot:11b}].tag.compilation.temp_read.id
data modify block ~ ~ ~ Items[{Slot:11b}].tag.compilation.temp_write.count set from block ~ ~ ~ Items[{Slot:11b}].tag.compilation.temp_read.Count
execute if data block ~ ~ ~ Items[{Slot:11b}].tag.compilation.temp_read{id:"minecraft:paper"} run data modify block ~ ~ ~ Items[{Slot:11b}].tag.compilation.temp_write set value {type: 1}
execute if data block ~ ~ ~ Items[{Slot:11b}].tag.compilation.temp_read{id:"minecraft:paper"} run data modify block ~ ~ ~ Items[{Slot:11b}].tag.compilation.temp_write.cmd set value 0
execute if data block ~ ~ ~ Items[{Slot:11b}].tag.compilation.temp_read{id:"minecraft:paper"} run data modify block ~ ~ ~ Items[{Slot:11b}].tag.compilation.temp_write.cmd set from block ~ ~ ~ Items[{Slot:11b}].tag.compilation.temp_read.tag.CustomModelData

data modify block ~ ~ ~ Items[{Slot:11b}].tag.compilation.translated append from block ~ ~ ~ Items[{Slot:11b}].tag.compilation.temp_write
data remove block ~ ~ ~ Items[{Slot:11b}].tag.compilation.merged[0]