#######
# Compiled from machines/compiler/compilation/modal_error.mcscript
# to .//data/computercraft/functions/machines/compiler/compilation/modal_error.mcfunction
#
# Generated by Minecraft Script for 1.13
######
