#######
# Compiled from functions/machines/compiler/gui.mcscript
# to .//data/computercraft/functions/machines/compiler/gui.mcfunction
#
# Generated by Minecraft Script for 1.13
######

execute unless data block ~ ~ ~ {Items:[{Slot:0b}]} run replaceitem block ~ ~ ~ container.0 minecraft:paper{CustomModelData:24101,display:{Name:'[{"text":""}]'}} 1

execute unless data block ~ ~ ~ {Items:[{Slot:1b}]} run replaceitem block ~ ~ ~ container.1 minecraft:paper{CustomModelData:24101,display:{Name:'[{"text":""}]'}} 1

execute unless data block ~ ~ ~ {Items:[{Slot:2b}]} run replaceitem block ~ ~ ~ container.2 minecraft:paper{CustomModelData:24101,display:{Name:'[{"text":""}]'}} 1

execute unless data block ~ ~ ~ {Items:[{Slot:3b}]} run replaceitem block ~ ~ ~ container.3 minecraft:paper{CustomModelData:24101,display:{Name:'[{"text":""}]'}} 1

execute unless data block ~ ~ ~ {Items:[{Slot:4b}]} run replaceitem block ~ ~ ~ container.4 minecraft:paper{CustomModelData:24101,display:{Name:'[{"text":""}]'}} 1

execute unless data block ~ ~ ~ {Items:[{Slot:5b}]} run replaceitem block ~ ~ ~ container.5 minecraft:paper{CustomModelData:24101,display:{Name:'[{"text":""}]'}} 1

execute unless data block ~ ~ ~ {Items:[{Slot:6b}]} run replaceitem block ~ ~ ~ container.6 minecraft:paper{CustomModelData:24101,display:{Name:'[{"text":""}]'}} 1

execute unless data block ~ ~ ~ {Items:[{Slot:7b}]} run replaceitem block ~ ~ ~ container.7 minecraft:paper{CustomModelData:24101,display:{Name:'[{"text":""}]'}} 1

execute unless data block ~ ~ ~ {Items:[{Slot:8b}]} run replaceitem block ~ ~ ~ container.8 minecraft:paper{CustomModelData:24101,display:{Name:'[{"text":""}]'}} 1

execute unless data block ~ ~ ~ {Items:[{Slot:9b}]} run replaceitem block ~ ~ ~ container.9 minecraft:paper{CustomModelData:24101,display:{Name:'[{"text":""}]'}} 1

execute unless data block ~ ~ ~ {Items:[{Slot:10b}]} run replaceitem block ~ ~ ~ container.10 minecraft:paper{CustomModelData:24101,display:{Name:'[{"text":""}]'}} 1

execute unless data block ~ ~ ~ {Items:[{Slot:12b}]} run replaceitem block ~ ~ ~ container.12 minecraft:paper{CustomModelData:24101,display:{Name:'[{"text":""}]'}} 1

execute if data entity @s {Tags:["compilation_empty"]} run replaceitem block ~ ~ ~ container.13 minecraft:paper{CustomModelData:24102,display:{Name:'[{"text":""}]'}} 1

execute if data entity @s {Tags:["compilation_merge"]} run replaceitem block ~ ~ ~ container.13 minecraft:paper{CustomModelData:24108,display:{Name:'[{"text":"Compiling","italic":false}]', Lore:['[{"text":"- Copy data","color":"dark_green","italic":false}]','[{"text":"- Merge pages","color":"yellow","italic":false}]','[{"text":"- Translate items","color":"white","italic":false}]','[{"text":"- Group commands","color":"white","italic":false}]','[{"text":"- Assign control blocks","color":"white","italic":false}]']}} 1

execute if data entity @s {Tags:["compilation_translating"]} run replaceitem block ~ ~ ~ container.13 minecraft:paper{CustomModelData:24108,display:{Name:'[{"text":"Compiling","italic":false}]', Lore:['[{"text":"- Copy data","color":"dark_green","italic":false}]','[{"text":"- Merge pages","color":"dark_green","italic":false}]','[{"text":"- Translate items","color":"yellow","italic":false}]','[{"text":"- Group commands","color":"white","italic":false}]','[{"text":"- Assign control blocks","color":"white","italic":false}]']}} 1

execute if data entity @s {Tags:["compilation_grouping"]} run replaceitem block ~ ~ ~ container.13 minecraft:paper{CustomModelData:24108,display:{Name:'[{"text":"Compiling","italic":false}]', Lore:['[{"text":"- Copy data","color":"dark_green","italic":false}]','[{"text":"- Merge pages","color":"dark_green","italic":false}]','[{"text":"- Translate items","color":"dark_green","italic":false}]','[{"text":"- Group commands","color":"yellow","italic":false}]','[{"text":"- Assign control blocks","color":"white","italic":false}]']}} 1

execute if data entity @s {Tags:["compilation_controls"]} run replaceitem block ~ ~ ~ container.13 minecraft:paper{CustomModelData:24108,display:{Name:'[{"text":"Compiling","italic":false}]', Lore:['[{"text":"- Copy data","color":"dark_green","italic":false}]','[{"text":"- Merge pages","color":"dark_green","italic":false}]','[{"text":"- Translate items","color":"dark_green","italic":false}]','[{"text":"- Group commands","color":"dark_green","italic":false}]','[{"text":"- Assign control blocks","color":"yellow","italic":false}]']}} 1

execute if data entity @s {Tags:["compilation_done"]} run replaceitem block ~ ~ ~ container.13 minecraft:paper{CustomModelData:24102,display:{Name:'[{"text":"Compiling","italic":false}]', Lore:['[{"text":"- Copy data","color":"dark_green","italic":false}]','[{"text":"- Merge pages","color":"dark_green","italic":false}]','[{"text":"- Translate items","color":"dark_green","italic":false}]','[{"text":"- Group commands","color":"dark_green","italic":false}]','[{"text":"- Assign control blocks","color":"dark_green","italic":false}]']}} 1

execute if data entity @s {Tags:["compilation_error"]} run replaceitem block ~ ~ ~ container.13 minecraft:paper{CustomModelData:24109,display:{Name:'[{"text":"Compilation error!", "color":"red", "italic": false}]',Lore:[]}} 1

execute unless data block ~ ~ ~ {Items:[{Slot:14b}]} run replaceitem block ~ ~ ~ container.14 minecraft:paper{CustomModelData:24101,display:{Name:'[{"text":""}]'}} 1

execute unless data block ~ ~ ~ {Items:[{Slot:16b}]} run replaceitem block ~ ~ ~ container.16 minecraft:paper{CustomModelData:24101,display:{Name:'[{"text":""}]'}} 1

execute unless data block ~ ~ ~ {Items:[{Slot:17b}]} run replaceitem block ~ ~ ~ container.17 minecraft:paper{CustomModelData:24101,display:{Name:'[{"text":""}]'}} 1

execute unless data block ~ ~ ~ {Items:[{Slot:18b}]} run replaceitem block ~ ~ ~ container.18 minecraft:paper{CustomModelData:24101,display:{Name:'[{"text":""}]'}} 1

execute unless data block ~ ~ ~ {Items:[{Slot:19b}]} run replaceitem block ~ ~ ~ container.19 minecraft:paper{CustomModelData:24101,display:{Name:'[{"text":""}]'}} 1

execute unless data block ~ ~ ~ {Items:[{Slot:20b}]} run replaceitem block ~ ~ ~ container.20 minecraft:paper{CustomModelData:24101,display:{Name:'[{"text":""}]'}} 1

execute unless data block ~ ~ ~ {Items:[{Slot:21b}]} run replaceitem block ~ ~ ~ container.21 minecraft:paper{CustomModelData:24101,display:{Name:'[{"text":""}]'}} 1

execute unless data block ~ ~ ~ {Items:[{Slot:22b}]} run replaceitem block ~ ~ ~ container.22 minecraft:paper{CustomModelData:24101,display:{Name:'[{"text":""}]'}} 1

execute unless data block ~ ~ ~ {Items:[{Slot:23b}]} run replaceitem block ~ ~ ~ container.23 minecraft:paper{CustomModelData:24101,display:{Name:'[{"text":""}]'}} 1

execute unless data block ~ ~ ~ {Items:[{Slot:24b}]} run replaceitem block ~ ~ ~ container.24 minecraft:paper{CustomModelData:24101,display:{Name:'[{"text":""}]'}} 1

execute unless data block ~ ~ ~ {Items:[{Slot:25b}]} run replaceitem block ~ ~ ~ container.25 minecraft:paper{CustomModelData:24101,display:{Name:'[{"text":""}]'}} 1

execute unless data block ~ ~ ~ {Items:[{Slot:26b}]} run replaceitem block ~ ~ ~ container.26 minecraft:paper{CustomModelData:24101,display:{Name:'[{"text":""}]'}} 1
