#######
# Compiled from functions/machines/robot/parse_inventory.mcscript
# to .//data/computercraft/functions/machines/robot/parse_inventory.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute as @e[tag=CC_Robot_Body] at @s store result score @s slot0 run data get entity @s HandItems[0].tag.code.1[0].tag.CustomModelData
execute as @e[tag=CC_Robot_Body] at @s store result score @s slot1 run data get entity @s HandItems[0].tag.code.1[1].tag.CustomModelData
execute as @e[tag=CC_Robot_Body] at @s store result score @s slot2 run data get entity @s HandItems[0].tag.code.1[2].tag.CustomModelData
execute as @e[tag=CC_Robot_Body] at @s store result score @s slot3 run data get entity @s HandItems[0].tag.code.1[3].tag.CustomModelData
execute as @e[tag=CC_Robot_Body] at @s store result score @s slot4 run data get entity @s HandItems[0].tag.code.1[4].tag.CustomModelData
execute as @e[tag=CC_Robot_Body] at @s store result score @s slot5 run data get entity @s HandItems[0].tag.code.1[5].tag.CustomModelData
execute as @e[tag=CC_Robot_Body] at @s store result score @s slot6 run data get entity @s HandItems[0].tag.code.1[6].tag.CustomModelData
execute as @e[tag=CC_Robot_Body] at @s store result score @s slot7 run data get entity @s HandItems[0].tag.code.1[7].tag.CustomModelData
execute as @e[tag=CC_Robot_Body] at @s store result score @s slot8 run data get entity @s HandItems[0].tag.code.1[8].tag.CustomModelData
execute as @e[tag=CC_Robot_Body] at @s store result score @s slot9 run data get entity @s HandItems[0].tag.code.1[9].tag.CustomModelData
execute as @e[tag=CC_Robot_Body] at @s store result score @s slot10 run data get entity @s HandItems[0].tag.code.1[10].tag.CustomModelData
execute as @e[tag=CC_Robot_Body] at @s store result score @s slot11 run data get entity @s HandItems[0].tag.code.1[11].tag.CustomModelData
execute as @e[tag=CC_Robot_Body] at @s store result score @s slot12 run data get entity @s HandItems[0].tag.code.1[12].tag.CustomModelData
execute as @e[tag=CC_Robot_Body] at @s store result score @s slot13 run data get entity @s HandItems[0].tag.code.1[13].tag.CustomModelData
execute as @e[tag=CC_Robot_Body] at @s store result score @s slot14 run data get entity @s HandItems[0].tag.code.1[14].tag.CustomModelData
execute as @e[tag=CC_Robot_Body] at @s store result score @s slot15 run data get entity @s HandItems[0].tag.code.1[15].tag.CustomModelData
execute as @e[tag=CC_Robot_Body] at @s store result score @s slot16 run data get entity @s HandItems[0].tag.code.1[16].tag.CustomModelData
execute as @e[tag=CC_Robot_Body] at @s store result score @s slot17 run data get entity @s HandItems[0].tag.code.1[17].tag.CustomModelData
execute as @e[tag=CC_Robot_Body] at @s store result score @s slot18 run data get entity @s HandItems[0].tag.code.1[18].tag.CustomModelData
execute as @e[tag=CC_Robot_Body] at @s store result score @s slot19 run data get entity @s HandItems[0].tag.code.1[19].tag.CustomModelData
execute as @e[tag=CC_Robot_Body] at @s store result score @s slot20 run data get entity @s HandItems[0].tag.code.1[20].tag.CustomModelData
execute as @e[tag=CC_Robot_Body] at @s store result score @s slot21 run data get entity @s HandItems[0].tag.code.1[21].tag.CustomModelData
execute as @e[tag=CC_Robot_Body] at @s store result score @s slot22 run data get entity @s HandItems[0].tag.code.1[22].tag.CustomModelData
execute as @e[tag=CC_Robot_Body] at @s store result score @s slot23 run data get entity @s HandItems[0].tag.code.1[23].tag.CustomModelData
execute as @e[tag=CC_Robot_Body] at @s store result score @s slot24 run data get entity @s HandItems[0].tag.code.1[24].tag.CustomModelData
execute as @e[tag=CC_Robot_Body] at @s store result score @s slot25 run data get entity @s HandItems[0].tag.code.1[25].tag.CustomModelData
execute as @e[tag=CC_Robot_Body] at @s store result score @s slot26 run data get entity @s HandItems[0].tag.code.1[26].tag.CustomModelData