#######
# Compiled from data/computercraft_crafting/functions/main.mcscript
# to .//data/computercraft_crafting/functions/create.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute as @s[nbt={FireworksItem:{tag:{CustomModelData:24003}}}] as @p run function computercraft_crafting:creations/1
execute as @s[nbt={FireworksItem:{tag:{CustomModelData:24004}}}] as @p run function computercraft_crafting:creations/2
execute as @s[nbt={FireworksItem:{tag:{CustomModelData:24005}}}] as @p run function computercraft_crafting:creations/3
execute as @s[nbt={FireworksItem:{tag:{CustomModelData:24006}}}] as @p run function computercraft_crafting:creations/4
execute as @s[nbt={FireworksItem:{tag:{CustomModelData:24007}}}] as @p run function computercraft_crafting:creations/5
kill @s
