#######
# Compiled from data/computercraft_crafting/functions/main.mcscript
# to .//data/computercraft_crafting/functions/main.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute as @e[type=firework_rocket,nbt={FireworksItem:{tag:{computercraft_craftingBlock:1}}}] at @s unless block ~ ~ ~ air if block ~0.4 ~ ~ air run tp @s ~0.5 ~ ~
execute as @e[type=firework_rocket,nbt={FireworksItem:{tag:{computercraft_craftingBlock:1}}}] at @s unless block ~ ~ ~ air if block ~-0.4 ~ ~ air run tp @s ~-0.5 ~ ~
execute as @e[type=firework_rocket,nbt={FireworksItem:{tag:{computercraft_craftingBlock:1}}}] at @s unless block ~ ~ ~ air if block ~ ~ ~-0.4 air run tp @s ~ ~ ~-0.5
execute as @e[type=firework_rocket,nbt={FireworksItem:{tag:{computercraft_craftingBlock:1}}}] at @s unless block ~ ~ ~ air if block ~ ~ ~0.4 air run tp @s ~ ~ ~0.5
execute as @e[type=firework_rocket,nbt={FireworksItem:{tag:{computercraft_craftingBlock:1}}}] at @s unless block ~ ~ ~ air if block ~ ~-0.4 ~ air run tp @s ~ ~-0.5 ~
execute as @e[type=firework_rocket,nbt={FireworksItem:{tag:{computercraft_craftingBlock:1}}}] at @s unless block ~ ~ ~ air if block ~ ~0.4 ~ air run tp @s ~ ~0.5 ~
execute as @e[type=firework_rocket,nbt={FireworksItem:{tag:{computercraft_craftingBlock:1}}}] at @s align xyz if block ~ ~ ~ air run function computercraft_crafting:create
execute as @e[tag=isCustomBlock,tag=block1] at @s if block ~ ~ ~ air run function computercraft_crafting:break/1
execute as @e[type=firework_rocket,nbt={FireworksItem:{tag:{computercraft_craftingBlock:2}}}] at @s unless block ~ ~ ~ air if block ~0.4 ~ ~ air run tp @s ~0.5 ~ ~
execute as @e[type=firework_rocket,nbt={FireworksItem:{tag:{computercraft_craftingBlock:2}}}] at @s unless block ~ ~ ~ air if block ~-0.4 ~ ~ air run tp @s ~-0.5 ~ ~
execute as @e[type=firework_rocket,nbt={FireworksItem:{tag:{computercraft_craftingBlock:2}}}] at @s unless block ~ ~ ~ air if block ~ ~ ~-0.4 air run tp @s ~ ~ ~-0.5
execute as @e[type=firework_rocket,nbt={FireworksItem:{tag:{computercraft_craftingBlock:2}}}] at @s unless block ~ ~ ~ air if block ~ ~ ~0.4 air run tp @s ~ ~ ~0.5
execute as @e[type=firework_rocket,nbt={FireworksItem:{tag:{computercraft_craftingBlock:2}}}] at @s unless block ~ ~ ~ air if block ~ ~-0.4 ~ air run tp @s ~ ~-0.5 ~
execute as @e[type=firework_rocket,nbt={FireworksItem:{tag:{computercraft_craftingBlock:2}}}] at @s unless block ~ ~ ~ air if block ~ ~0.4 ~ air run tp @s ~ ~0.5 ~
execute as @e[type=firework_rocket,nbt={FireworksItem:{tag:{computercraft_craftingBlock:2}}}] at @s align xyz if block ~ ~ ~ air run function computercraft_crafting:create
execute as @e[tag=isCustomBlock,tag=block2] at @s if block ~ ~ ~ air run function computercraft_crafting:break/2
execute as @e[type=firework_rocket,nbt={FireworksItem:{tag:{computercraft_craftingBlock:3}}}] at @s unless block ~ ~ ~ air if block ~0.4 ~ ~ air run tp @s ~0.5 ~ ~
execute as @e[type=firework_rocket,nbt={FireworksItem:{tag:{computercraft_craftingBlock:3}}}] at @s unless block ~ ~ ~ air if block ~-0.4 ~ ~ air run tp @s ~-0.5 ~ ~
execute as @e[type=firework_rocket,nbt={FireworksItem:{tag:{computercraft_craftingBlock:3}}}] at @s unless block ~ ~ ~ air if block ~ ~ ~-0.4 air run tp @s ~ ~ ~-0.5
execute as @e[type=firework_rocket,nbt={FireworksItem:{tag:{computercraft_craftingBlock:3}}}] at @s unless block ~ ~ ~ air if block ~ ~ ~0.4 air run tp @s ~ ~ ~0.5
execute as @e[type=firework_rocket,nbt={FireworksItem:{tag:{computercraft_craftingBlock:3}}}] at @s unless block ~ ~ ~ air if block ~ ~-0.4 ~ air run tp @s ~ ~-0.5 ~
execute as @e[type=firework_rocket,nbt={FireworksItem:{tag:{computercraft_craftingBlock:3}}}] at @s unless block ~ ~ ~ air if block ~ ~0.4 ~ air run tp @s ~ ~0.5 ~
execute as @e[type=firework_rocket,nbt={FireworksItem:{tag:{computercraft_craftingBlock:3}}}] at @s align xyz if block ~ ~ ~ air run function computercraft_crafting:create
execute as @e[tag=isCustomBlock,tag=block3] at @s if block ~ ~ ~ air run function computercraft_crafting:break/3
execute as @e[type=firework_rocket,nbt={FireworksItem:{tag:{computercraft_craftingBlock:4}}}] at @s unless block ~ ~ ~ air if block ~0.4 ~ ~ air run tp @s ~0.5 ~ ~
execute as @e[type=firework_rocket,nbt={FireworksItem:{tag:{computercraft_craftingBlock:4}}}] at @s unless block ~ ~ ~ air if block ~-0.4 ~ ~ air run tp @s ~-0.5 ~ ~
execute as @e[type=firework_rocket,nbt={FireworksItem:{tag:{computercraft_craftingBlock:4}}}] at @s unless block ~ ~ ~ air if block ~ ~ ~-0.4 air run tp @s ~ ~ ~-0.5
execute as @e[type=firework_rocket,nbt={FireworksItem:{tag:{computercraft_craftingBlock:4}}}] at @s unless block ~ ~ ~ air if block ~ ~ ~0.4 air run tp @s ~ ~ ~0.5
execute as @e[type=firework_rocket,nbt={FireworksItem:{tag:{computercraft_craftingBlock:4}}}] at @s unless block ~ ~ ~ air if block ~ ~-0.4 ~ air run tp @s ~ ~-0.5 ~
execute as @e[type=firework_rocket,nbt={FireworksItem:{tag:{computercraft_craftingBlock:4}}}] at @s unless block ~ ~ ~ air if block ~ ~0.4 ~ air run tp @s ~ ~0.5 ~
execute as @e[type=firework_rocket,nbt={FireworksItem:{tag:{computercraft_craftingBlock:4}}}] at @s align xyz if block ~ ~ ~ air run function computercraft_crafting:create
execute as @e[tag=isCustomBlock,tag=block4] at @s if block ~ ~ ~ air run function computercraft_crafting:break/4
execute as @e[tag=isCustomBlock] run data merge entity @s {Fire:23000s}
