#######
# Compiled from data/computercraft_crafting/functions/printer_return_paper.mcscript
# to .//data/computercraft_crafting/functions/printer_return_paper.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute if score @s paper matches 0 run summon minecraft:item ~ ~0.5 ~ {Item:{id:"minecraft:paper",Count:0}}
execute if score @s paper matches 0 run scoreboard players remove @s paper 0

execute if score @s paper matches 1 run summon minecraft:item ~ ~0.5 ~ {Item:{id:"minecraft:paper",Count:1}}
execute if score @s paper matches 1 run scoreboard players remove @s paper 1

execute if score @s paper matches 2 run summon minecraft:item ~ ~0.5 ~ {Item:{id:"minecraft:paper",Count:2}}
execute if score @s paper matches 2 run scoreboard players remove @s paper 2

execute if score @s paper matches 3 run summon minecraft:item ~ ~0.5 ~ {Item:{id:"minecraft:paper",Count:3}}
execute if score @s paper matches 3 run scoreboard players remove @s paper 3

execute if score @s paper matches 4 run summon minecraft:item ~ ~0.5 ~ {Item:{id:"minecraft:paper",Count:4}}
execute if score @s paper matches 4 run scoreboard players remove @s paper 4

execute if score @s paper matches 5 run summon minecraft:item ~ ~0.5 ~ {Item:{id:"minecraft:paper",Count:5}}
execute if score @s paper matches 5 run scoreboard players remove @s paper 5

execute if score @s paper matches 6 run summon minecraft:item ~ ~0.5 ~ {Item:{id:"minecraft:paper",Count:6}}
execute if score @s paper matches 6 run scoreboard players remove @s paper 6

execute if score @s paper matches 7 run summon minecraft:item ~ ~0.5 ~ {Item:{id:"minecraft:paper",Count:7}}
execute if score @s paper matches 7 run scoreboard players remove @s paper 7

execute if score @s paper matches 8 run summon minecraft:item ~ ~0.5 ~ {Item:{id:"minecraft:paper",Count:8}}
execute if score @s paper matches 8 run scoreboard players remove @s paper 8

execute if score @s paper matches 9 run summon minecraft:item ~ ~0.5 ~ {Item:{id:"minecraft:paper",Count:9}}
execute if score @s paper matches 9 run scoreboard players remove @s paper 9

execute if score @s paper matches 10 run summon minecraft:item ~ ~0.5 ~ {Item:{id:"minecraft:paper",Count:10}}
execute if score @s paper matches 10 run scoreboard players remove @s paper 10

execute if score @s paper matches 11 run summon minecraft:item ~ ~0.5 ~ {Item:{id:"minecraft:paper",Count:11}}
execute if score @s paper matches 11 run scoreboard players remove @s paper 11

execute if score @s paper matches 12 run summon minecraft:item ~ ~0.5 ~ {Item:{id:"minecraft:paper",Count:12}}
execute if score @s paper matches 12 run scoreboard players remove @s paper 12

execute if score @s paper matches 13 run summon minecraft:item ~ ~0.5 ~ {Item:{id:"minecraft:paper",Count:13}}
execute if score @s paper matches 13 run scoreboard players remove @s paper 13

execute if score @s paper matches 14 run summon minecraft:item ~ ~0.5 ~ {Item:{id:"minecraft:paper",Count:14}}
execute if score @s paper matches 14 run scoreboard players remove @s paper 14

execute if score @s paper matches 15 run summon minecraft:item ~ ~0.5 ~ {Item:{id:"minecraft:paper",Count:15}}
execute if score @s paper matches 15 run scoreboard players remove @s paper 15

execute if score @s paper matches 16 run summon minecraft:item ~ ~0.5 ~ {Item:{id:"minecraft:paper",Count:16}}
execute if score @s paper matches 16 run scoreboard players remove @s paper 16

execute if score @s paper matches 17 run summon minecraft:item ~ ~0.5 ~ {Item:{id:"minecraft:paper",Count:17}}
execute if score @s paper matches 17 run scoreboard players remove @s paper 17

execute if score @s paper matches 18 run summon minecraft:item ~ ~0.5 ~ {Item:{id:"minecraft:paper",Count:18}}
execute if score @s paper matches 18 run scoreboard players remove @s paper 18

execute if score @s paper matches 19 run summon minecraft:item ~ ~0.5 ~ {Item:{id:"minecraft:paper",Count:19}}
execute if score @s paper matches 19 run scoreboard players remove @s paper 19

execute if score @s paper matches 20 run summon minecraft:item ~ ~0.5 ~ {Item:{id:"minecraft:paper",Count:20}}
execute if score @s paper matches 20 run scoreboard players remove @s paper 20

execute if score @s paper matches 21 run summon minecraft:item ~ ~0.5 ~ {Item:{id:"minecraft:paper",Count:21}}
execute if score @s paper matches 21 run scoreboard players remove @s paper 21

execute if score @s paper matches 22 run summon minecraft:item ~ ~0.5 ~ {Item:{id:"minecraft:paper",Count:22}}
execute if score @s paper matches 22 run scoreboard players remove @s paper 22

execute if score @s paper matches 23 run summon minecraft:item ~ ~0.5 ~ {Item:{id:"minecraft:paper",Count:23}}
execute if score @s paper matches 23 run scoreboard players remove @s paper 23

execute if score @s paper matches 24 run summon minecraft:item ~ ~0.5 ~ {Item:{id:"minecraft:paper",Count:24}}
execute if score @s paper matches 24 run scoreboard players remove @s paper 24

execute if score @s paper matches 25 run summon minecraft:item ~ ~0.5 ~ {Item:{id:"minecraft:paper",Count:25}}
execute if score @s paper matches 25 run scoreboard players remove @s paper 25

execute if score @s paper matches 26 run summon minecraft:item ~ ~0.5 ~ {Item:{id:"minecraft:paper",Count:26}}
execute if score @s paper matches 26 run scoreboard players remove @s paper 26

execute if score @s paper matches 27 run summon minecraft:item ~ ~0.5 ~ {Item:{id:"minecraft:paper",Count:27}}
execute if score @s paper matches 27 run scoreboard players remove @s paper 27

execute if score @s paper matches 28 run summon minecraft:item ~ ~0.5 ~ {Item:{id:"minecraft:paper",Count:28}}
execute if score @s paper matches 28 run scoreboard players remove @s paper 28

execute if score @s paper matches 29 run summon minecraft:item ~ ~0.5 ~ {Item:{id:"minecraft:paper",Count:29}}
execute if score @s paper matches 29 run scoreboard players remove @s paper 29

execute if score @s paper matches 30 run summon minecraft:item ~ ~0.5 ~ {Item:{id:"minecraft:paper",Count:30}}
execute if score @s paper matches 30 run scoreboard players remove @s paper 30

execute if score @s paper matches 31 run summon minecraft:item ~ ~0.5 ~ {Item:{id:"minecraft:paper",Count:31}}
execute if score @s paper matches 31 run scoreboard players remove @s paper 31

execute if score @s paper matches 32 run summon minecraft:item ~ ~0.5 ~ {Item:{id:"minecraft:paper",Count:32}}
execute if score @s paper matches 32 run scoreboard players remove @s paper 32

execute if score @s paper matches 33 run summon minecraft:item ~ ~0.5 ~ {Item:{id:"minecraft:paper",Count:33}}
execute if score @s paper matches 33 run scoreboard players remove @s paper 33

execute if score @s paper matches 34 run summon minecraft:item ~ ~0.5 ~ {Item:{id:"minecraft:paper",Count:34}}
execute if score @s paper matches 34 run scoreboard players remove @s paper 34

execute if score @s paper matches 35 run summon minecraft:item ~ ~0.5 ~ {Item:{id:"minecraft:paper",Count:35}}
execute if score @s paper matches 35 run scoreboard players remove @s paper 35

execute if score @s paper matches 36 run summon minecraft:item ~ ~0.5 ~ {Item:{id:"minecraft:paper",Count:36}}
execute if score @s paper matches 36 run scoreboard players remove @s paper 36

execute if score @s paper matches 37 run summon minecraft:item ~ ~0.5 ~ {Item:{id:"minecraft:paper",Count:37}}
execute if score @s paper matches 37 run scoreboard players remove @s paper 37

execute if score @s paper matches 38 run summon minecraft:item ~ ~0.5 ~ {Item:{id:"minecraft:paper",Count:38}}
execute if score @s paper matches 38 run scoreboard players remove @s paper 38

execute if score @s paper matches 39 run summon minecraft:item ~ ~0.5 ~ {Item:{id:"minecraft:paper",Count:39}}
execute if score @s paper matches 39 run scoreboard players remove @s paper 39

execute if score @s paper matches 40 run summon minecraft:item ~ ~0.5 ~ {Item:{id:"minecraft:paper",Count:40}}
execute if score @s paper matches 40 run scoreboard players remove @s paper 40

execute if score @s paper matches 41 run summon minecraft:item ~ ~0.5 ~ {Item:{id:"minecraft:paper",Count:41}}
execute if score @s paper matches 41 run scoreboard players remove @s paper 41

execute if score @s paper matches 42 run summon minecraft:item ~ ~0.5 ~ {Item:{id:"minecraft:paper",Count:42}}
execute if score @s paper matches 42 run scoreboard players remove @s paper 42

execute if score @s paper matches 43 run summon minecraft:item ~ ~0.5 ~ {Item:{id:"minecraft:paper",Count:43}}
execute if score @s paper matches 43 run scoreboard players remove @s paper 43

execute if score @s paper matches 44 run summon minecraft:item ~ ~0.5 ~ {Item:{id:"minecraft:paper",Count:44}}
execute if score @s paper matches 44 run scoreboard players remove @s paper 44

execute if score @s paper matches 45 run summon minecraft:item ~ ~0.5 ~ {Item:{id:"minecraft:paper",Count:45}}
execute if score @s paper matches 45 run scoreboard players remove @s paper 45

execute if score @s paper matches 46 run summon minecraft:item ~ ~0.5 ~ {Item:{id:"minecraft:paper",Count:46}}
execute if score @s paper matches 46 run scoreboard players remove @s paper 46

execute if score @s paper matches 47 run summon minecraft:item ~ ~0.5 ~ {Item:{id:"minecraft:paper",Count:47}}
execute if score @s paper matches 47 run scoreboard players remove @s paper 47

execute if score @s paper matches 48 run summon minecraft:item ~ ~0.5 ~ {Item:{id:"minecraft:paper",Count:48}}
execute if score @s paper matches 48 run scoreboard players remove @s paper 48

execute if score @s paper matches 49 run summon minecraft:item ~ ~0.5 ~ {Item:{id:"minecraft:paper",Count:49}}
execute if score @s paper matches 49 run scoreboard players remove @s paper 49

execute if score @s paper matches 50 run summon minecraft:item ~ ~0.5 ~ {Item:{id:"minecraft:paper",Count:50}}
execute if score @s paper matches 50 run scoreboard players remove @s paper 50

execute if score @s paper matches 51 run summon minecraft:item ~ ~0.5 ~ {Item:{id:"minecraft:paper",Count:51}}
execute if score @s paper matches 51 run scoreboard players remove @s paper 51

execute if score @s paper matches 52 run summon minecraft:item ~ ~0.5 ~ {Item:{id:"minecraft:paper",Count:52}}
execute if score @s paper matches 52 run scoreboard players remove @s paper 52

execute if score @s paper matches 53 run summon minecraft:item ~ ~0.5 ~ {Item:{id:"minecraft:paper",Count:53}}
execute if score @s paper matches 53 run scoreboard players remove @s paper 53

execute if score @s paper matches 54 run summon minecraft:item ~ ~0.5 ~ {Item:{id:"minecraft:paper",Count:54}}
execute if score @s paper matches 54 run scoreboard players remove @s paper 54

execute if score @s paper matches 55 run summon minecraft:item ~ ~0.5 ~ {Item:{id:"minecraft:paper",Count:55}}
execute if score @s paper matches 55 run scoreboard players remove @s paper 55

execute if score @s paper matches 56 run summon minecraft:item ~ ~0.5 ~ {Item:{id:"minecraft:paper",Count:56}}
execute if score @s paper matches 56 run scoreboard players remove @s paper 56

execute if score @s paper matches 57 run summon minecraft:item ~ ~0.5 ~ {Item:{id:"minecraft:paper",Count:57}}
execute if score @s paper matches 57 run scoreboard players remove @s paper 57

execute if score @s paper matches 58 run summon minecraft:item ~ ~0.5 ~ {Item:{id:"minecraft:paper",Count:58}}
execute if score @s paper matches 58 run scoreboard players remove @s paper 58

execute if score @s paper matches 59 run summon minecraft:item ~ ~0.5 ~ {Item:{id:"minecraft:paper",Count:59}}
execute if score @s paper matches 59 run scoreboard players remove @s paper 59

execute if score @s paper matches 60 run summon minecraft:item ~ ~0.5 ~ {Item:{id:"minecraft:paper",Count:60}}
execute if score @s paper matches 60 run scoreboard players remove @s paper 60

execute if score @s paper matches 61 run summon minecraft:item ~ ~0.5 ~ {Item:{id:"minecraft:paper",Count:61}}
execute if score @s paper matches 61 run scoreboard players remove @s paper 61

execute if score @s paper matches 62 run summon minecraft:item ~ ~0.5 ~ {Item:{id:"minecraft:paper",Count:62}}
execute if score @s paper matches 62 run scoreboard players remove @s paper 62

execute if score @s paper matches 63 run summon minecraft:item ~ ~0.5 ~ {Item:{id:"minecraft:paper",Count:63}}
execute if score @s paper matches 63 run scoreboard players remove @s paper 63

execute if score @s paper matches 64.. run summon minecraft:item ~ ~0.5 ~ {Item:{id:"minecraft:paper",Count:64}}
execute if score @s paper matches 64.. run scoreboard players remove @s paper 64
execute if score @s paper matches 64.. run function computercraft_crafting:printer_return_paper
