#######
# Compiled from machines/robot/enqueue/enqueue.mcscript
# to .//data/computercraft/functions/machines/robot/enqueue/enqueue.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute if data entity @s HandItems[0].tag.execution.to_enqueue_reversed[] run data modify entity @s HandItems[0].tag.execution.queue prepend from entity @s HandItems[0].tag.execution.to_enqueue_reversed[0]
execute if data entity @s HandItems[0].tag.execution.to_enqueue_reversed[] run data remove entity @s HandItems[0].tag.execution.to_enqueue_reversed[0]
execute if data entity @s HandItems[0].tag.execution.to_enqueue_reversed[] run function computercraft:machines/robot/enqueue/enqueue
