#######
# Compiled from machines/robot/enqueue/main.mcscript
# to .//data/computercraft/functions/machines/robot/enqueue/main.mcfunction
#
# Generated by Minecraft Script for 1.13
######
data modify entity @s HandItems[0].tag.execution.to_enqueue_reversed set value []
function computercraft:machines/robot/enqueue/reverse
function computercraft:machines/robot/enqueue/enqueue