#######
# Compiled from functions/machines/robot/cmd.mcscript
# to .//data/computercraft/functions/machines/robot/cmd/back.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute if block ~ ~2 ~1 air if score @s currentRotation matches 0 run tp @s ~ ~ ~-1
execute if block ~-1 ~2 ~ air if score @s currentRotation matches 90 run tp @s ~1 ~ ~
execute if block ~ ~2 ~-1 air if score @s currentRotation matches 180 run tp @s ~ ~ ~1
execute if block ~1 ~2 ~ air if score @s currentRotation matches 270 run tp @s ~-1 ~ ~
