#######
# Compiled from machines/robot/cmd/detect_block_modal.mcscript
# to .//data/computercraft/functions/machines/robot/cmd/detect_block_modal.mcfunction
#
# Generated by Minecraft Script for 1.13
######
