#######
# Compiled from machines/robot/cmd/cmd.mcscript
# to .//data/computercraft/functions/machines/robot/cmd/down.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute if block ~ ~1 ~ air run tp @s ~ ~-1 ~
