#######
# Compiled from functions/machines/robot/cmd.mcscript
# to .//data/computercraft/functions/machines/robot/cmd/mine.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute if score @s currentRotation matches 0 run setblock ~ ~2 ~1 minecraft:air destroy
execute if score @s currentRotation matches 90 run setblock ~-1 ~2 ~ minecraft:air destroy
execute if score @s currentRotation matches 180 run setblock ~ ~2 ~-1 minecraft:air destroy
execute if score @s currentRotation matches 270 run setblock ~1 ~2 ~ minecraft:air destroy
execute if score @s currentRotation matches 0 positioned ~ ~2 ~1 as @e[distance=0..1.2,sort=nearest,limit=1,type=!minecraft:armor_stand] run function computercraft:common/damage
execute if score @s currentRotation matches 90 positioned ~-1 ~2 ~1 as @e[distance=0..1.2,sort=nearest,limit=1,type=!minecraft:armor_stand] run function computercraft:common/damage
execute if score @s currentRotation matches 180 positioned ~ ~2 ~-1 as @e[distance=0..1.2,sort=nearest,limit=1,type=!minecraft:armor_stand] run function computercraft:common/damage
execute if score @s currentRotation matches 270 positioned ~1 ~2 ~ as @e[distance=0..1.2,sort=nearest,limit=1,type=!minecraft:armor_stand] run function computercraft:common/damage