#######
# Compiled from machines/robot/cmd/cmd.mcscript
# to .//data/computercraft/functions/machines/robot/cmd/mine.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute if score @s currentRotation matches 0 run setblock ~ ~2 ~1 minecraft:air destroy
execute if score @s currentRotation matches 90 run setblock ~-1 ~2 ~ minecraft:air destroy
execute if score @s currentRotation matches 180 run setblock ~ ~2 ~-1 minecraft:air destroy
execute if score @s currentRotation matches 270 run setblock ~1 ~2 ~ minecraft:air destroy
