#######
# Compiled from machines/robot/cmd/cmd.mcscript
# to .//data/computercraft/functions/machines/robot/cmd/mine_down.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute unless block ~ ~1 ~0 minecraft:bedrock unless block ~ ~1 ~0 minecraft:end_portal unless block ~ ~1 ~0 minecraft:end_portal_frame run setblock ~ ~1 ~0 minecraft:air destroy

