#######
# Compiled from machines/robot/cmd/cmd.mcscript
# to .//data/computercraft/functions/machines/robot/cmd/mine.mcfunction
#
# Generated by Minecraft Script for 1.13
######

execute if score @s currentRotation matches 0 unless block ~ ~2 ~1 minecraft:bedrock unless block ~ ~2 ~1 minecraft:end_portal unless block ~ ~2 ~1 minecraft:end_portal_frame run setblock ~ ~2 ~1 minecraft:air destroy

execute if score @s currentRotation matches 90 unless block ~-1 ~2 ~ minecraft:bedrock unless block ~-1 ~2 ~ minecraft:end_portal unless block ~-1 ~2 ~ minecraft:end_portal_frame run setblock ~-1 ~2 ~ minecraft:air destroy

execute if score @s currentRotation matches 180 unless block ~ ~2 ~-1 minecraft:bedrock unless block ~ ~2 ~-1 minecraft:end_portal unless block ~ ~2 ~-1 minecraft:end_portal_frame run setblock ~ ~2 ~-1 minecraft:air destroy

execute if score @s currentRotation matches 270 unless block ~1 ~2 ~ minecraft:bedrock unless block ~1 ~2 ~ minecraft:end_portal unless block ~1 ~2 ~ minecraft:end_portal_frame run setblock ~1 ~2 ~ minecraft:air destroy

