#######
# Compiled from functions/machines/robot/cmd.mcscript
# to .//data/computercraft/functions/machines/robot/cmd/right.mcfunction
#
# Generated by Minecraft Script for 1.13
######
tp @s ~ ~ ~ ~90 0
