#######
# Compiled from functions/machines/robot/cmd.mcscript
# to .//data/computercraft/functions/machines/robot/cmd/up.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute if block ~ ~3 ~ air run tp @s ~ ~1 ~
